#
# config file for B3.py
#

[base]
  tableName  = "B3"
  dbFileName = "B3.sqlite"

  defaultB3Link       = "https://redwoodempire.org/B3/latest.json"
  defaultMD5HashLink  = "https://redwoodempire.org/B3/latest.md5sum"
